openapi: 3.1.0
info:
  title: Customer Service API
  description: Provides customer data and operations.
  version: v1
servers:
- url: http://localhost:8080
  description: Generated server url
paths:
  /customers:
    get:
      tags:
      - customer-controller
      summary: Returns all customers
      description: Provides a list of all customers stored in the system
      operationId: getCustomers
      responses:
        "200":
          description: List was successfully retrieved
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/CustomerDto"
              examples:
                Example customer list:
                  description: Example customer list
                  value:
                  - id: 1
                    firstName: string
                    lastName: string
                    birthDate: 2025-04-05
                    email: string
        "500":
          description: Internal server error
          content:
            '*/*':
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/CustomerDto"
    put:
      tags:
      - customer-controller
      summary: Updates an existing customer
      description: Updates the data of an existing customer in the system
      operationId: updateCustomer
      requestBody:
        description: The updated data of the customer
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/CustomerDto"
            examples:
              customer_updated:
                description: customer_updated
                value:
                  id: 1
                  firstName: string
                  lastName: string
                  birthDate: 2025-04-05
                  email: string
              customer_updated_notFound:
                description: customer_updated_notFound
                value:
                  id: 999999999
                  firstName: string
                  lastName: string
                  birthDate: 2025-04-05
                  email: string
              customer_updated_invalid_firstName:
                description: customer_updated_invalid_firstName
                value:
                  id: 1
                  firstName: ""
                  lastName: string
                  birthDate: 2025-04-05
                  email: string
              customer_updated_invalid_lastName:
                description: customer_updated_invalid_lastName
                value:
                  id: 1
                  firstName: string
                  lastName: ""
                  birthDate: 2025-04-05
                  email: string
              customer_updated_invalid_birthDate:
                description: customer_updated_invalid_birthDate
                value:
                  id: 1
                  firstName: string
                  lastName: string
                  birthDate: ""
                  email: string
        required: true
      responses:
        "200":
          description: Customer successfully updated
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/CustomerDto"
              examples:
                customer_updated:
                  description: customer_updated
                  value: |
                    {
                      "id": {{ request.body/id }},
                      "firstName": "{{ request.body/firstName }}",
                      "lastName": "{{ request.body/lastName }}",
                      "birthDate": "{{ request.body/birthDate }}",
                      "email": "{{ request.body/email }}"
                    }
        "400":
          description: Invalid input data
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponse"
              examples:
                customer_updated_invalid_firstName:
                  description: Customer firstname is invalid
                  value:
                    message: Validierungsfehler
                    errors:
                      firstName: Vorname darf nicht leer sein
                customer_updated_invalid_lastName:
                  description: Customer lastname is invalid
                  value:
                    message: Validierungsfehler
                    errors:
                      lastName: Nachname darf nicht leer sein
                customer_updated_invalid_birthDate:
                  description: Customer birthDate is invalid
                  value:
                    message: Validierungsfehler
                    errors:
                      birthDate: Geburtsdatum ist ungültig
        "404":
          description: Customer not found
          content:
            application/json:
              examples:
                customer_updated_notFound:
                  description: Customer not found
      x-microcks-operation:
        delay: "25"
        dispatcherRules: |
          def customer = new groovy.json.JsonSlurper().parseText(mockRequest.requestContent);

          if (customer.id == null || customer.id == 999999999) {
              return "customer_updated_notFound";
          }

          if (customer.firstName == null || customer.firstName.trim() == "") {
            return "customer_updated_invalid_firstName";
          }

          if (customer.lastName == null || customer.lastName.trim() == "") {
            return "customer_updated_invalid_lastName";
          }

          if (customer.birthDate == null || customer.birthDate.trim() == "") {
              return "customer_updated_invalid_birthDate";
          }

          return "customer_updated";
        dispatcher: SCRIPT
    post:
      tags:
      - customer-controller
      summary: Creates a new customer
      description: Creates a new customer in the system
      operationId: createCustomer
      requestBody:
        description: The data of the customer to be created
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/CreateCustomerDto"
            examples:
              customer_created:
                description: customer_created
                value:
                  firstName: Max
                  lastName: Mustermann
                  birthDate: 2025-04-05
                  email: max.mustermann@web.de
              customer_created_invalid_firstName:
                description: customer_created_invalid_firstName
                value:
                  firstName: ""
                  lastName: Mustermann
                  birthDate: 2025-04-05
                  email: null
              customer_created_invalid_lastName:
                description: customer_created_invalid_lastName
                value:
                  firstName: string
                  lastName: ""
                  birthDate: 2025-04-05
                  email: null
              customer_created_invalid_birthDate:
                description: customer_created_invalid_birthDate
                value:
                  firstName: string
                  lastName: ""
                  birthDate: 2025-04-05
                  email: null
        required: true
      responses:
        "201":
          description: Customer successfully created
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/CustomerDto"
              examples:
                customer_created:
                  description: customer_created
                  value:
                    id: 1
                    firstName: string
                    lastName: string
                    birthDate: 2025-04-05
                    email: string
        "400":
          description: Invalid input data
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponse"
              examples:
                customer_created_invalid_firstName:
                  description: Customer firstname is invalid
                  value:
                    message: Validierungsfehler
                    errors:
                      firstName: Vorname darf nicht leer sein
                customer_created_invalid_lastName:
                  description: Customer lastname is invalid
                  value:
                    message: Validierungsfehler
                    errors:
                      lastName: Nachname darf nicht leer sein
                customer_created_invalid_birthDate:
                  description: Customer birthDate is invalid
                  value:
                    message: Validierungsfehler
                    errors:
                      birthDate: Geburtsdatum ist ungültig
        "500":
          description: Internal Server Error
          content:
            '*/*':
              schema:
                $ref: "#/components/schemas/CustomerDto"
      x-microcks-operation:
        delay: "25"
        dispatcherRules: |
          def customer = new groovy.json.JsonSlurper().parseText(mockRequest.requestContent);

          if (customer.firstName == null || customer.firstName.trim() == "") {
            return "customer_created_invalid_firstname";
          }

          if (customer.lastName == null || customer.lastName.trim() == "") {
            return "customer_created_invalid_lastname";
          }

          if (customer.birthDate == null || customer.birthDate.trim() == "")) {
              return "customer_created_invalid_birthDate";
          }

          return "customer_created";
        dispatcher: SCRIPT
  /customers/{id}:
    get:
      tags:
      - customer-controller
      summary: Retrieves a customer
      operationId: getCustomerById
      parameters:
      - name: id
        in: path
        description: The ID of the customer
        required: true
        schema:
          type: integer
          format: int64
        examples:
          customer_not_found:
            description: customer_not_found
            value: 9999999999
          customer_found:
            description: customer_found
            value: 1
      responses:
        "200":
          description: Customer found
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/CustomerDto"
              examples:
                customer_found:
                  description: customer_found
                  value:
                    id: 1
                    firstName: string
                    lastName: string
                    birthDate: 2025-04-05
                    email: string
        "404":
          description: Customer not found
          content:
            application/json:
              examples:
                customer_not_found:
                  description: customer_not_found
        "500":
          description: Internal Server Error
          content:
            '*/*':
              schema:
                $ref: "#/components/schemas/CustomerDto"
    delete:
      tags:
      - customer-controller
      summary: Deletes an existing customer
      description: Deletes an existing customer from the system
      operationId: deleteCustomer
      parameters:
      - name: id
        in: path
        description: The ID of the customer to be deleted
        required: true
        schema:
          type: integer
          format: int64
        examples:
          non_customer:
            description: non_customer
            value: 9999999999
          customer_deleted:
            description: customer_deleted
            value: 1
      responses:
        "204":
          description: Customer successfully deleted
          content:
            application/json:
              examples:
                customer_deleted:
                  description: customer_deleted
                non_customer:
                  description: non_customer
        "500":
          description: Internal Server Error
          content:
            '*/*':
              schema:
                type: object
components:
  schemas:
    ErrorResponse:
      type: object
      properties:
        message:
          type: string
          description: Error message
        errors:
          type: object
          additionalProperties:
            type: string
          description: Validation errors
      required:
        - errors
        - message
    CustomerDto:
      type: object
      properties:
        id:
          type: integer
          format: int64
          description: The ID of the customer
        firstName:
          type: string
          description: The first name of the customer
          minLength: 1
        lastName:
          type: string
          description: The last name of the customer
          minLength: 1
        birthDate:
          type: string
          format: date
          description: The birth date of the customer
        email:
          type: string
          description: The email of the customer
      required:
      - birthDate
      - firstName
      - id
      - lastName
    CreateCustomerDto:
      type: object
      properties:
        firstName:
          type: string
          minLength: 1
        lastName:
          type: string
          minLength: 1
        birthDate:
          type: string
          format: date
        email:
          type: string
      required:
      - birthDate
